spring.application.name=SmartLibrary
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/library_mgt?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret config (for simplicity in development)
app.jwt.secret=64D8A29AABC61B21CA14B8B9B167E19CE951AC4B9B884EA2623B68884C0F7DE9
app.jwt.expiration-ms=86400000
